services:
  laravel_7x:
    container_name: laravel_7x
    build: .
    volumes:
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - ./:/var/www/html/
    ports:
      - 8000:8000
volumes:
  vendor:
  node_modules:
